### ISSUE TITLE
clang format

### ISSUE THREAD

**Issue by mourner** [mapbox/wagyu#14]
Let's set up Clang formatter (e.g. pulling options from https://github.com/mapbox/mapbox-gl-native/blob/master/.clang-format), and then use that throughout the code so that it has consistent formatting style. cc @flippmoke

**Comment by flippmoke** [comment]
@mourner we already have this via `make indent` and @ericfischer put it together.

**Comment by mourner** [comment]
Ah cool. Can we move the style config to `.clang-format` file so that it's readable, and then decide on better formatting options?

**Comment by ericfischer** [comment]
I'm totally fine with something "better" if you have a "better" to suggest. I was just trying to get as close as possible to what it already looked like.

**Comment by mourner** [comment]
I think the gl-native settings are great, and are used throughout most of our C++ libraries — would be great to adopt that.

**Comment by ericfischer** [comment]
I would be comfortable with that style if it works for everyone else too.

**Comment by springmeyer** [comment]
👍 to gl-native settings and using a `.clang-format`.

**Comment by springmeyer** [comment]
For reference, osrm-backend is enforcing the format like https://github.com/Project-OSRM/osrm-backend/blob/master/scripts/format.sh with https://github.com/Project-OSRM/osrm-backend/blob/master/.travis.yml#L179-L182

**Comment by ericfischer** [comment]
Reformatted in 0138b75ab0fe2f
