### ISSUE TITLE
decide fixture-tester output

### ISSUE THREAD

**Issue by tcql** [mapbox/wagyu#24]
Right now fixture-tester takes input as flat arrays of rings: 

```json
[
    [[-79102, 0],[-70312, -55285],[85254, -30747],[58008, 80592],[-79102, 0]],
    [[44824, 42149],[51855, -21089],[-65918, -32502],[-50098, 4394],[44824, 42149]],
    [[-40430, -3076],[-26367, -18454],[34277, -4834],[33838, 17136],[-40430, -3076]]
]
```

with no extra nesting for boundaries vs holes. 

At the moment, it outputs _nested_ structures:
```json
[
    [
        [[-70312,-55285],[-79102,0],[58008,80592],[85254,-30747],[-70312,-55285]],
        [[-65918,-32502],[51855,-21089],[44824,42149],[-50098,4394],[-65918,-32502]]
    ],
    [
        [[10547,-19771],[-5728,-13819],[-26367,-18454],[-40430,-3076],[-12792,4446],[4834,19771],[19761,13305],[33838,17136],[34277,-4834],[18998,-8265],[10547,-19771]]
    ]
]
```

. Should we keep input and output formats the same? Nested output is useful for converting to geojson, since a geojson converter would only need to wrap the structures in geometry objects. A flat list of rings means that geojson converters would need to detect which rings are holes within which other polygons. 

/cc @jakepruitt @flippmoke @ericfischer @mourner

**Comment by ericfischer** [comment]
I'd say nested output is the right thing *if* clients are expected to be able to trust wagyu about which rings are interior to which other rings, which seems like the right thing if it indeed gets the relationships right.

**Comment by springmeyer** [comment]
> if clients are expected to be able to trust wagyu about which rings are interior to which other rings

Yes, definitely. So I'm also 👍 to nesting.

**Comment by tcql** [comment]
🆗 sounds good to me, it'll make life easier down the line
