### ISSUE TITLE
Test creation from fuzzer

### ISSUE THREAD

**Issue by flippmoke** [mapbox/wagyu#30]
The ideal solution here would be the creation of a new test fixture each time that fuzzer fails (with a flag to do so). Basically it is very difficult to debug single tests in the fuzzer currently because they might be many iterations from the initial seed value.

/cc @ericfischer

**Comment by ericfischer** [comment]
OK @flippmoke, so you want it to just autogenerate a file in the tests directory whenever it breaks?

**Comment by ericfischer** [comment]
OK, fuzzing will now create a file in the tests directory with the failed polygon. 3e47e7f882ba855
