### ISSUE TITLE
Removing atan2 - Better Self Intersection Process Ordering

### ISSUE THREAD

**Issue by flippmoke** [mapbox/wagyu#36]
A new way to determine the order of self intersections processing order at a single point that does not use `std::atan2` would be wonderful for many reasons. One is that `std::atan2` is slow to calculate and the accuracy of its results is questionable. 

## The Fundemental Assumption

The resulting rings from the vatti processing are **garuanteed** to never result in the path of a ring crossing with itself. While the path might be collinear or share intersection points that need to be cleaned up, it does not ever result in an "crossing intersection".

The image below shows a single ring - this is *not* a crossing intersection because the pairing of any two segments (one being towards, one being away) does not result in the path crossing over itself.
<img width="513" alt="screen shot 2016-10-06 at 1 28 48 pm" src="https://cloud.githubusercontent.com/assets/1794907/19165296/dbd12050-8bc8-11e6-856f-7d19fe7fafb7.png">

The next image however is an example of a crossing intersection. 

<img width="527" alt="screen shot 2016-10-06 at 1 34 12 pm" src="https://cloud.githubusercontent.com/assets/1794907/19165497/a12f8d6e-8bc9-11e6-9af3-d8ad254280a1.png">

Notice how no pair of towards and away paths can be selected such that the paths do not cross.

This is important for one reason - splitting a ring into two distinct rings is the critical part of self intersection processing and *if an intersection is crossing the two resulting rings will be crossing each other such that one ring could be partial inside the other*. This makes it **MUCH** more difficult to properly determine parent child relationship of the resulting rings.

## When crossing intersections occur

Crossing intersections could possibly occur when a self intersection of a ring at a single point has *more then 2* paths through the point. The following is an example of where this can occur.

<img width="453" alt="screen shot 2016-10-06 at 1 47 31 pm" src="https://cloud.githubusercontent.com/assets/1794907/19165978/80b2849a-8bcb-11e6-970f-271d2b4c6525.png">

It is difficult to visualize the original path with out "spreading out" the points that intersect ever so slightly (this is shown below).

<img width="657" alt="screen shot 2016-10-06 at 1 49 52 pm" src="https://cloud.githubusercontent.com/assets/1794907/19166084/dcc99002-8bcb-11e6-9b38-4eace7ca8768.png">

Assuming that we labeled each of the intersection points from left to right in the picture above as `A, B, C, D`. Lets explore how the order of the self intersection processing can result in intersections.

### What does self intersection processing do?

At its core self intersections are corrected by swapping where each intersection point will travel to next. This can be seen [here](https://github.com/mapbox/wagyu/blob/9dab09d15112280d847a94e30dc1a700c282745b/include/mapbox/geometry/wagyu/topology_correction.hpp#L721-L727). 

```
    // split the polygon into two ...
    point_ptr<T> op3 = op->prev;
    point_ptr<T> op4 = op2->prev;
    op->prev = op4;
    op4->next = op;
    op2->prev = op3;
    op3->next = op2;
```

If we processed `A` and `B` together first it will result in the creation of a new ring as shown below:

<img width="452" alt="screen shot 2016-10-06 at 2 00 08 pm" src="https://cloud.githubusercontent.com/assets/1794907/19166466/3bf31214-8bcd-11e6-9dae-90555aa500bf.png">

This is proper because the resulting two rings -- are either **completely within or completely outside of the other ring**. Notice as well that when we zoom in there are still no crossing intersections. 

<img width="678" alt="screen shot 2016-10-06 at 2 09 25 pm" src="https://cloud.githubusercontent.com/assets/1794907/19166797/9dd27fdc-8bce-11e6-921a-a5415c9fddff.png">

However, lets say we attempt now to process `B` and `D`. Hint: this will result in a crossing intersection.

<img width="434" alt="screen shot 2016-10-06 at 2 16 10 pm" src="https://cloud.githubusercontent.com/assets/1794907/19166998/7d64b494-8bcf-11e6-840d-5d38003326c0.png">

## Preventing Crossing Intersections

In order to prevent this from occuring, self intersections should only be performed between any two paths selected for another intersection where there is no other path that would bisect them! To determine this the angles of each of the segments is first [measured and sorted](https://github.com/mapbox/wagyu/blob/9dab09d15112280d847a94e30dc1a700c282745b/include/mapbox/geometry/wagyu/topology_correction.hpp#L1174). After this [a pair of paths is found that satisfies this requirement](https://github.com/mapbox/wagyu/blob/9dab09d15112280d847a94e30dc1a700c282745b/include/mapbox/geometry/wagyu/topology_correction.hpp#L1187).

However, this is an often repeated process and repeated calls to [atan2](https://github.com/mapbox/wagyu/blob/9dab09d15112280d847a94e30dc1a700c282745b/include/mapbox/geometry/wagyu/topology_correction.hpp#L957-L958) are required. 

Optimizing the code could result in performance increases such that atan2 could be called less, but if a sorting method that avoided floating point numbers could be avoided this would be much better as currently this methodology [seems to be making indeterminate results in the outputs of wagyu](https://github.com/mapbox/wagyu/issues/35).

/cc @mourner @ericfischer

**Comment by mourner** [comment]
The way I've seen this done in many papers is with [point vs segment orientation checks](http://www.geeksforgeeks.org/orientation-3-ordered-points/). It's a simple integer arithmetic calculation that avoids trigonometry while providing a way to sort segments stemming from one point by "angle".

**Comment by flippmoke** [comment]
Should be fixed by https://github.com/mapbox/wagyu/commit/ae50700e62a8d6b8690172d5c9ed19119a17eea2
