### ISSUE TITLE
Handle SIGINT in fuzzer or exit cleanly at max iterations

### ISSUE THREAD

**Issue by springmeyer** [mapbox/wagyu#40]
I'm working on looking at the % of code coverage the fuzzer hits. The way llvm-cov works if you ctrl-c a process no coverage data is output. So I'm going to look at adding SIGINT handling to the fuzzer. Another option I considered was adding a max iterations option to the fuzzer and gracefully exiting when that is hit.

**Comment by flippmoke** [comment]
I think a max iterations option is perhaps a better option, notice that counts and iterations are slightly different currently, but we could perhaps change them to be the same.

**Comment by springmeyer** [comment]
> notice that counts and iterations are slightly different currently

Say more?

**Comment by flippmoke** [comment]
One Iteration is 16 tests: 
https://github.com/mapbox/wagyu/blob/master/tests/fuzzer.cpp#L196

One count is one test:
https://github.com/mapbox/wagyu/blob/master/tests/fuzzer.cpp#L226

**Comment by flippmoke** [comment]
I added a clean exit for fuzzer in https://github.com/mapbox/wagyu/commit/975613f412ed6649ad83ad91918da9389a2f4284

**Comment by springmeyer** [comment]
👍
