### ISSUE TITLE
Wrong points retained in polygon with many collinear edges

### ISSUE THREAD

**Issue by ericfischer** [mapbox/wagyu#58]
So that I don't lose track of it…

* [Input](https://gist.githubusercontent.com/flippmoke/804ccbf8962258331ec90f0a2f5bdf37/raw/88aa42f092cc436412688a56484f0248f07089d8/input.geojson)
* [Current output](https://gist.githubusercontent.com/flippmoke/804ccbf8962258331ec90f0a2f5bdf37/raw/88aa42f092cc436412688a56484f0248f07089d8/current_output.geojson)

![collinear](https://cloud.githubusercontent.com/assets/1951835/21406956/fe9623d8-c782-11e6-8142-e01aac9d6ec3.png)

Reproduce with

```
make build-fixture-tester && ./fixture-tester -t union -f non_zero input.geojson.txt
```

**Comment by flippmoke** [comment]
@ericfischer note that the fixture command there isn't the same as you would need for the input / output as they haven't been added to geometry-test-data

**Comment by ericfischer** [comment]
Oh, sure, sorry, I just pasted your example.

**Comment by ericfischer** [comment]
Working on this in https://github.com/mapbox/wagyu/pull/59, which appears to fix the immediate problem but expose some other problem with `tests/geometry-test-data/input-polyjson/stairstep.json`:

```
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: Trying to find intersection of lines that do not intersect
```

**Comment by ericfischer** [comment]
Confusingly,

```
make build-fixture-tester && ./fixture-tester -t union -f non_zero tests/geometry-test-data/input-polyjson/stairstep.json
```

does *not* fail; only tests that union or intersect the stairstep test with another polygon do.

**Comment by ericfischer** [comment]
I must be doing something else wrong anyway because the changes eliminate all the stairstepping of `stairstep.json` even when it doesn't crash.
