### ISSUE TITLE
No usage of `reverse_output` in push_ring_to_polygon

### ISSUE THREAD

**Issue by springmeyer** [mapbox/wagyu#64]
It appears that `push_ring_to_polygon` has a `reverse_output` argument that is never passed and therefore the code for this is fully uncovered. Should this be removed?

**Comment by flippmoke** [comment]
No,  I think we simply need to add more test coverage for this option, this is important for a user who might want to create a geometry with out having to manually reverse rings after the output is created.

**Comment by springmeyer** [comment]
> important for a user who might want to create a geometry with out having to manually reverse rings after the output is created.

Why exactly is that usecase important? Is this a theoretical need or is there an actual downstream use currently that is not covered in the unit tests?

**Comment by flippmoke** [comment]
This is useful in the situation that the output geometry expects a different output orientation then what is expected. Geometry.hpp currently doesn't specify specifically expected winding orders and therefore in some applications it would be possible that a different orientation would be wanted. This is a simple way to provide output that follows a specific orientation.
