### ISSUE TITLE
dispose_out_points never called

### ISSUE THREAD

**Issue by springmeyer** [mapbox/wagyu#65]
The `dispose_out_points` function is never called in the fixture tests or unit tests. Are we missing test for this code, or is it unneeded?

**Comment by flippmoke** [comment]
Some of the code added covers theoretical edge cases in some areas of the code that have been hit in the past but other changes removed coverage. This is one of those sections and it worries me to remove it currently. I looked at removing it during the changes made in #56 but I was unable to remove it with confidence yet. It is still on my todo list.
