### ISSUE TITLE
Recent large code coverage changes

### ISSUE THREAD

**Issue by springmeyer** [mapbox/wagyu#90]
After #89 merged coverage dropped from 94% to 44%:

Before:

<img width="953" alt="screen shot 2018-12-08 at 7 43 35 am" src="https://user-images.githubusercontent.com/20300/49687809-654b5980-fabd-11e8-972c-401b6884ada7.png">

After:

<img width="968" alt="screen shot 2018-12-08 at 7 43 41 am" src="https://user-images.githubusercontent.com/20300/49687811-67adb380-fabd-11e8-899f-afee47e56847.png">

@flippmoke is this expected?

**Comment by Komzpa** [comment]
Coverage is at 2%:

![image](https://user-images.githubusercontent.com/810638/50420302-ab871380-0846-11e9-9bae-d126470b1d79.png)
