### ISSUE TITLE
Mapbox Issue with snapping of LineString to the actual road

### ISSUE THREAD

**Issue by lebyanelm** [mapbox/wagyu#99]
I am not sure if this is an issue or not, cause Google does not seem to have much on Mapbox documentation and examples.

So am trying to show route directions in Mapbox using the Directions API, but the geometry coordinates returned back does not snap to the road properly like how an actual navigation App would do, it's showing a straight line and totally ignores the corners and curves of roads
![Screenshot 2019-09-20 at 23 29 49](https://user-images.githubusercontent.com/29936760/65360114-f0d24900-dbfe-11e9-900d-a19d9f12d504.png)

, maybe am doing this wrong or am missing function or something.

**Comment by flippmoke** [comment]
I think you have posted this in the wrong repo, I am closing this.
